# https://docs.docker.com/compose/compose-file/
version: "3"
services:
  payara:
    build: Docker-Images/Payara-image
    links:
      - database:db
    ports:
      - "8080:8080"
      - "4848:4848"

  database:
    build: Docker-Images/DB-image
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "7070:8080"

  phpmyadmin:
    build: Docker-Images/PHPmyAdmin-image
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "6060:80"
    links:
      - database:db