# https://docs.docker.com/compose/compose-file/
version: "3"
services:
  payara:
    build: Docker-Images/Payara-image
    links:
      - mysql:db
    ports:
      - 8080:8080
      - 4848:4848

  mysql:
    build: Docker-Images/DB-image
    command: --max_allowed_packet=500M
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "3306:3306"

  phpmyadmin:
    build: Docker-Images/PHPmyAdmin-image
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "6060:80"
    links:
      - mysql:db